# docker-compose.yml
version: "3.9"
services:
  react-app:
    image: react-app:latest
    container_name: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
  django-app:
    image: django-app:latest
    container_name: django-app
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app:delegated
      