# Generated by Django 5.0.1 on 2024-03-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='group_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.group')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'Group'), ('quarters', 'Quarters'), ('semifinals', 'Semifinals'), ('final', 'Final')], max_length=16)),
                ('local_goals', models.PositiveSmallIntegerField(null=True)),
                ('away_goals', models.PositiveSmallIntegerField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_match_set', to='tournaments.team')),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_match_set', to='tournaments.team')),
                ('looser_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser_match_set', to='tournaments.team')),
                ('winner_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_match_set', to='tournaments.team')),
            ],
        ),
    ]
