# Generated by Django 5.0.1 on 2024-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_match_looser_team_remove_match_winner_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(null=True),
        ),
    ]
